# Generated by Django 5.0.1 on 2024-01-16 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('about', models.TextField()),
                ('type', models.CharField(choices=[('IT', 'it'), ('Non it ', 'non it'), ('Other', 'other')], max_length=100)),
                ('added_data', models.BooleanField(default=True)),
                ('added_dateTime', models.DateField(auto_now=True)),
            ],
        ),
    ]
