# Generated by Django 5.0.1 on 2024-01-16 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='added_dateTime',
            new_name='active',
        ),
    ]
